import { describe, it } from 'vitest'

describe('§2.2 OpenClaw Implementation', () => {
  it.todo('MUST establish a WebSocket connection to the OpenClaw gateway URL specified in config')
  it.todo('MUST generate an Ed25519 keypair on first use and store it to {dataDir}/agent-backend/device-identity.json')
  it.todo('MUST sign authentication payloads with the device private key')
  it.todo('MUST send the device token in the initial WS handshake')
  it.todo('MUST implement automatic reconnection with exponential backoff')
  it.todo('MUST default initial delay to 1000ms')
  it.todo('MUST default maximum delay to 30000ms')
  it.todo('MUST apply jitter by default to prevent thundering herd')
  it.todo('MUST emit backend.status with disconnected immediately on connection loss')
  it.todo('MUST emit backend.status with connecting when a reconnection attempt begins')
  it.todo('MUST emit backend.status with connected when reconnection succeeds')
  it.todo('MUST translate OpenClaw streaming messages to chat.stream events')
  it.todo('MUST translate OpenClaw turn completion to chat.turn events with a fully parsed ParsedTurn')
  it.todo('MUST translate OpenClaw tool call/result messages to chat.work events')
  it.todo('MUST translate OpenClaw thinking block messages to chat.work events with type thinking')
  it.todo('MUST translate OpenClaw status transitions to chat.status events')
  it.todo('MUST translate OpenClaw compaction messages to chat.compacting events')
  it.todo('MUST translate OpenClaw error messages to chat.error events')
  it.todo('MUST strip thinking blocks from streamed text')
  it.todo('MUST preserve code blocks even if they contain thinking-like tags')
  it.todo('MUST emit chat.error with retryAfterMs set to the gateway indicated retry delay')
  it.todo('MUST automatically retry the request after the indicated delay')
  it.todo('MUST emit backend.status with error and include metadata about pending pairing request')
  it.todo('MUST NOT block or crash when pairing is pending — MUST continue reconnection attempts')
  it.todo('MUST read gateway URL from config module at path agentBackend.openclaw.gatewayUrl')
  it.todo('MUST support hot-reload: disconnect from old URL and reconnect to new URL on config change')
  it.todo('MUST reload conversation history when agent transitions from working to idle')
  it.todo('MUST debounce history reload (300ms) to avoid unnecessary refetches during rapid state changes')
  it.todo('MUST emit reloaded history as a session.info event')
})
