import { describe, it } from 'vitest'

describe('§8.1 Header', () => {
  it.todo('MUST render a fixed-position top bar')
  it.todo('MUST include thread drawer toggle IconButton with hamburger icon')
  it.todo('MUST call setDrawerOpen on drawer toggle click')
  it.todo('MUST include ConnectionBadge passed as prop')
  it.todo('MUST show current thread display name')
  it.todo('MUST show primary entity name for entity-bound threads')
  it.todo('MUST show clickable +N indicator for multi-entity threads')
  it.todo('MUST expand to show all bound entities when +N is clicked')
  it.todo('MUST show subagent count Badge when subagents are active')
  it.todo('MUST include view switcher with tabs for each ViewMode')
  it.todo('MUST highlight active view with accent underline or background')
  it.todo('MUST call setViewMode when a view tab is clicked')
  it.todo('MUST include settings IconButton with gear icon')
  it.todo('MUST call setSettingsOpen(true) on settings click')
  it.todo('MUST use var(--c-bg-raised) background')
  it.todo('MUST use var(--c-border) bottom border')
  it.todo('MUST apply safe-area inset padding at top for mobile notches')
})
