import { describe, it } from 'vitest'

describe('§8.8 Meeting REST API', () => {
  it.todo('§8.8 GET /api/orgs/:orgId/meetings MUST list meetings (paginated, filterable)')
  it.todo('§8.8 POST /api/orgs/:orgId/meetings MUST create meeting manually')
  it.todo('§8.8 POST /api/orgs/:orgId/meetings/import MUST import external meeting')
  it.todo('§8.8 GET /api/orgs/:orgId/meetings/context MUST return aggregated meeting context')
  it.todo('§8.8 GET /api/orgs/:orgId/meetings/:id MUST get meeting detail')
  it.todo('§8.8 PATCH /api/orgs/:orgId/meetings/:id MUST update meeting metadata')
  it.todo('§8.8 DELETE /api/orgs/:orgId/meetings/:id MUST delete meeting + recordings + transcript')
  it.todo('§8.8 POST /api/orgs/:orgId/meetings/:id/transcribe MUST re-trigger transcription')
  it.todo('§8.8 POST /api/orgs/:orgId/meetings/:id/summarize MUST re-trigger summarization')
  it.todo('§8.8 PATCH /api/orgs/:orgId/meetings/:id/speakers MUST update speaker labels')
  it.todo('§8.8 GET /api/orgs/:orgId/meetings/:id/transcript MUST get full transcript')
  it.todo('§8.8 GET /api/orgs/:orgId/meetings/:id/audio MUST stream merged audio')
  it.todo('§8.8 GET /api/orgs/:orgId/speakers MUST return org-wide speaker label history')
  it.todo('§8.8 GET /api/orgs/:orgId/recordings MUST list recordings with meeting/thread filters')
  it.todo('§8.8 POST /api/orgs/:orgId/recordings MUST upload recording')
  it.todo('§8.8 GET /api/orgs/:orgId/recordings/:id MUST return recording metadata')
  it.todo('§8.8 GET /api/orgs/:orgId/recordings/:id/audio MUST stream audio with Range support')
  it.todo('§8.8 DELETE /api/orgs/:orgId/recordings/:id MUST delete recording')
  it.todo('§8.8 GET /api/orgs/:orgId/recordings/search MUST search transcripts')
  it.todo('§8.8 GET /api/threads/:key/meetings MUST return meetings bound to a thread')
  it.todo('§8.8 GET /api/system/transcription/queue MUST return transcription queue status')
})
