import { describe, it } from 'vitest'

describe('Planning Service', () => {
  describe('2.1 Planning Service', () => {
    it.todo('MUST be created via createPlanningService(bus, dataDir, deps)')
    it.todo('MUST inject dependencies: { issueTracker, getConfig }')
    it.todo('MUST NOT import from issues module directly')
    it.todo('MUST build dependency graph by listing issues from issue tracker')
    it.todo('MUST parse dependency references from issue bodies')
    it.todo('MUST construct graph via graph engine')
    it.todo('MUST cache dependency index to disk')
    it.todo('MUST support sync — refresh dependency index from provider data')
    it.todo('MUST perform incremental sync — only reparse issues whose bodyHash changed')
    it.todo('MUST listen for issue.created events and update dependency index')
    it.todo('MUST listen for issue.updated events and update dependency index')
    it.todo('MUST listen for issue.synced events and update dependency index')
    it.todo('MUST expose getGraph query scoped to an org')
    it.todo('MUST expose getCriticalPath query scoped to an org')
    it.todo('MUST expose getBlocked query scoped to an org')
    it.todo('MUST expose getReady query scoped to an org')
    it.todo('MUST expose getParallelSets query scoped to an org')
    it.todo('MUST expose getImpact query scoped to an org')
    it.todo('MUST expose getCompletion query scoped to an org')
    it.todo('MUST support creating issues with dependencies via createIssue')
    it.todo('MUST format dependency references into issue body before creating')
    it.todo('MUST support batch operations via decompose')
    it.todo('MUST create each issue via issue tracker during decompose')
    it.todo('MUST include dependency references in issue bodies during decompose')
    it.todo('MUST emit planning.graph.updated event')
    it.todo('MUST emit planning.sync.completed event')
    it.todo('MUST emit planning.cycle.detected event')
    it.todo('MUST expose status() returning ModuleStatus')
  })
})
