import { describe, it } from 'vitest'

describe('§4.5 InputArea', () => {
  it.todo('MUST provide a multi-line textarea that auto-resizes vertically')
  it.todo('MUST have minimum height of one line and maximum height of 200px')
  it.todo('MUST send message on Enter (without modifier keys)')
  it.todo('Shift+Enter MUST insert a newline')
  it.todo('MUST support file attachments via drag-and-drop')
  it.todo('MUST support file attachments via paste (images from clipboard)')
  it.todo('MUST support file attachments via file picker (📎 icon button)')
  it.todo('MUST show attached files as removable Chip components above input')
  it.todo('MUST show filename, file size, and remove button on each chip')
  it.todo('Image attachments SHOULD show thumbnail preview')
  it.todo('MUST include voice recording button (🎤) that triggers push-to-talk')
  it.todo('MUST show recording timer (MM:SS) when recording is active')
  it.todo('MUST show pulsing animation (animate-mic-pulse) on microphone button during recording')
  it.todo('MUST change microphone button to stop button (⬛) during recording')
  it.todo('MUST include send button (➤) that is disabled when input is empty and no files attached')
  it.todo('MUST enable send button when there is text or at least one attachment')
  it.todo('MUST include abort button (⬛) visible only when agentStatus is working or thinking')
  it.todo('MUST replace send button with abort button when visible')
  it.todo('MUST call abortChat() on abort button click')
  it.todo('Up arrow MUST cycle backward through previously sent messages when cursor is at beginning')
  it.todo('Down arrow MUST cycle forward through message history')
  it.todo('Message history MUST be persisted per-thread in localStorage key sovereign:history:{threadKey}')
  it.todo('History MUST be limited to last 50 messages per thread')
  it.todo('Input content MUST be auto-saved to localStorage key sovereign:scratchpad:{threadKey} (debounced 500ms)')
  it.todo('Scratchpad MUST be restored when switching threads')
  it.todo('Scratchpad MUST be cleared when a message is sent')
  it.todo('MUST be fixed at the bottom of the chat view')
  it.todo('MUST apply safe-area inset padding at bottom for mobile devices')
  it.todo('MUST show current agent status inline (Working… or Thinking…)')
})
