import { describe, it } from 'vitest'

describe('§3.2 Chat Store', () => {
  it.todo('MUST expose turns: Accessor<ParsedTurn[]>')
  it.todo('MUST expose streamingHtml: Accessor<string>')
  it.todo('MUST expose agentStatus: Accessor<AgentStatus>')
  it.todo('MUST expose liveWork: Accessor<WorkItem[]>')
  it.todo('MUST expose liveThinkingText: Accessor<string>')
  it.todo('MUST expose compacting: Accessor<boolean>')
  it.todo('MUST expose isRetryCountdownActive: Accessor<boolean>')
  it.todo('MUST expose retryCountdownSeconds: Accessor<number>')
  it.todo('MUST expose startRetryCountdown(seconds) that decrements every second')
  it.todo('MUST expose clearRetryCountdown() that cancels countdown and resets state')
  it.todo('sendMessage MUST add an optimistic pending turn to turns immediately')
  it.todo('sendMessage MUST clear the input scratchpad for the current thread')
  it.todo('abortChat MUST send chat.abort via WS and update agentStatus to idle')
  it.todo('MUST subscribe to chat WS channel for chat.stream messages')
  it.todo('MUST subscribe to chat WS channel for chat.turn messages')
  it.todo('MUST subscribe to chat WS channel for chat.status messages')
  it.todo('MUST subscribe to chat WS channel for chat.work messages')
  it.todo('MUST subscribe to chat WS channel for chat.compacting messages')
  it.todo('MUST subscribe to chat WS channel for chat.error messages')
  it.todo('MUST subscribe to chat WS channel for chat.session.info messages')
  it.todo('MUST replace optimistic pending turn with confirmed turn on chat.turn')
  it.todo('MUST call startRetryCountdown when chat.error arrives with retryAfterMs')
  it.todo('MUST replace turns with provided history on chat.session.info')
  it.todo('MUST clear all state when thread changes')
  it.todo('MUST send chat.session.switch via WS when thread changes')
  it.todo('MUST await chat.session.info response to populate turns after thread switch')
  it.todo('MUST accept threadKey as a reactive accessor via initChatStore')
})
